
package hash;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IService {


    /**
     * 
     * @param salt
     * @param value
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Hash", action = "http://tempuri.org/IService/Hash")
    @WebResult(name = "HashResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Hash", targetNamespace = "http://tempuri.org/", className = "hash.Hash")
    @ResponseWrapper(localName = "HashResponse", targetNamespace = "http://tempuri.org/", className = "hash.HashResponse")
    public String hash(
        @WebParam(name = "value", targetNamespace = "http://tempuri.org/")
        String value,
        @WebParam(name = "salt", targetNamespace = "http://tempuri.org/")
        String salt);

}
