
package salt;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetRandomString0", action = "http://tempuri.org/IService/GetRandomString0")
    @WebResult(name = "GetRandomString0Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetRandomString0", targetNamespace = "http://tempuri.org/", className = "salt.GetRandomString0")
    @ResponseWrapper(localName = "GetRandomString0Response", targetNamespace = "http://tempuri.org/", className = "salt.GetRandomString0Response")
    public String getRandomString0();

    /**
     * 
     * @param length
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetRandomString", action = "http://tempuri.org/IService/GetRandomString")
    @WebResult(name = "GetRandomStringResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetRandomString", targetNamespace = "http://tempuri.org/", className = "salt.GetRandomString")
    @ResponseWrapper(localName = "GetRandomStringResponse", targetNamespace = "http://tempuri.org/", className = "salt.GetRandomStringResponse")
    public String getRandomString(
        @WebParam(name = "Length", targetNamespace = "http://tempuri.org/")
        String length);

}
