package client.model.genre;

/*
    Complete list of anime genres retrieved from : Anirecs

 */
public enum Genres {
    ACTION("Action","The action genre is a class of creative works characterized by emphasis on exciting action sequences. This does not always mean they exclude character development or story-telling. The genre encompasses action fiction, action films, action games and analogous media in other formats such as manga and anime. There are many sub-genres, including martial arts action, extreme sports action, car chases and vehicles, suspense action, and action comedy, with each focusing in more detail on its own type and flavour of action. It is usually possible to tell from the creative style of an action sequence, the genre of the entire creative works. For example, the style of a combat sequence will indicate whether the entire works is an action adventure, or martial arts. Action is mainly defined by a lot of focus on any kind of movement."),
    ADVENTURE("Adventure"," Also another popular genre of Anime, as the same suggests it deals alot with characters moving around and exploring  new places, these anime tend to be very long and drawn out but the characters typically have a solid background. The anime itself usually has a well formed story-line but due to the nature of this genre viewers often get bored and annoyed at the slow progression. Overall its a pretty decent anime genre and allows pretty much every other genre to almost seamlessly integrate themselves into it. Common mixtures are: Adventure – Action, Adventure-Historical (due to its uncanny ability to tell a story) and Adventure – Slice of Life. Examples of this Genre are Kino no Tabi, Fullmetal Alchemist, and Pokemon."),
    ANIMATION("Animation","Okay, this one is a bit difficult to explain seeing as Anime are all Animated, when one says Animation it normally refers to an American made Animated Series such as Samurai Jack, Spawn and the Penguins of Madagascar. By right they are not animes since the definition of an anime is ” a Japanese style of motion-picture animation, characterized by highly stylized, colorful art, futuristic settings violence and sexuality” ~ Dictionary.com , but are very often mistaken as such."),
    BISHOUNEN("Bishounen","This genre is pretty rare in the West but back in japan it has proved to be a successful alley, it deals with\n" +
            "a young male whose beauty exceeds gender somewhat and is mostly targeted at the girls and women in japan. This genre often includes a strong sense of homosexuality and has very unique social relationships. It is normally paired with slice of life and examples are Ouran High School Host Club and Fruits Basket."),
    COMEDY("Comedy","The most predominantly Used Anime genres yet is almost never used on its own, as its name implies deals with usually light humor although it is very easily overdone. This is is usually achieved by the use of Props, Character Designs and the composition of the Japanese Language. Common combinations are Action Comedy’s or Romantic Comedy’s, such as Sayanora Zetsubou Sensei,\n" +
            "Full Metal Panic and Lucky Star."),
    DEMONS("Demons","Pretty common genre, deals with evil spirits, demons, witches etc, normally combined with the action (my personal favorite combination (demon + Action) ) or adventure genres. Examples are Inuyasha, Yu Yu Hakusho and Ichiban Ushiro no Daimaou"),
    DRAMA("Drama","Suspenseful, shocking and full of emotion, the Drama anime genre is one of the most appreciated anime Genres, characters and the plot are usually well developed and viewers are very easily swept up with emotion and side with one character or a group of characters, it is usually well paired with Romance  as well as Adventure, in fact, the Drama anime genre is very often synonymous with the Romance genre, a few common examples are Darker than Black, Death note and Monster."),
    ECCHI("Ecchi","This is the PG-13 of anime, although some shows drive it to the extreme where it could be Rated R, it is usually frivolous and lighthearted with the use of implied sexual innuendos. The ecchi genre does now show sexual intercourse nor the Primary Sexual Organs but leaves it up to the viewer’s imagination. This genre is usually used as  fan service (due to its popularity among anime lovers alike) and recently the ratio at which anime is created with ecchi related content is drastically increasing. It is often incorporated with the comedy, harem and shounen/seinen genres, examples are (jeez theres just so many) Elfen Leid, Freezing, Zero no Tsukaima, Futari Ecchi and Ladies vs Butlers"),
    FANTASY("Fantasy","Magic worlds, magical powers and monsters, these are the main components that make up fantasy anime. It is usually combined with the adventure, action and history genres. Mythology and folklore is usually the foundation on which this genre is based upon, unfortunately the characters often have very poor backgrounds but the art is almost always breathtaking with unique scenery and magnificent character detail. It is normally paired with the adventure, harem and romance genres, common examples are Fairy Tail, Fullmetal Alchemist and Inuyasha."),
    GAME("Game","As the name says, it basically involves the characters playing some sort of game. (normally card / monster based). It on its own cannot be a genre, it has to accompany another which is normally either Adventure or Psychological. Examples are Yu-Gi-Oh, Duel Masters and Bakugan."),
    HAREM("Harem","Almost always accompanied by the comedy or romance genres, Harem is more or less the scenario where the main character is surrounded amorously by three or more members of the opposite sex, usually with the protagonist being a guy. Almost always comical and has a certain degree of love/romance. Anime such as Da Capo, Love Hina and School Days."),
    HENTAI("Hentai","This is the Rated MA Stuff, basically anime po.rnography, unlike its softer sister ecchi it shows all the sexual organs and well as intercourse. This genre more often than not has no background and poorly developed characters with most of the content being from explicit scenes. Almost always paired with harem with a male protagonist. Examples include bible. black and mistreated bride."),
    HISTORICAL("Historical","nime based on a particular time period, very often the Edo/Tokugawa period in Japan where the shoguns ruled the country(althought it can be american based).  Characters are often fashioned from well known figures in Japanese past such as commanders and even the shoguns themselves. Almost always paired with the samurai genre. Examples include Rurouni Kenshin, Baccano and Shigurui."),
    HORROR("Horror","Despite the name, the horror anime isn’t very scary, instead it implies alot of bloodshed and mutilation, i suppose a better word would have been gruesome. Often used with the Drama, demon or psychological genres. Eg. Mnemosyne and Higurashi no Naku Koro ni."),
    JOSEI("Josei","A very rare (at least in the west) genre aimed at the adult woman (ages 18-40). They are normally themed about living the life of an ordinary woman although some can be held in a school setting. The animation is very mature and realistic (eg. no sparkly eyes), it tends to focus very realistically on romance, and character relationships. Paradise Kiss, Honey and Clover."),
    KIDS("Kids","As the name implies, lighthearted and ‘kiddy’ themes, usually paired with comedy. Characters are normally small and somewhat cute. Digimon, Pokemon."),
    ROMANCE("Romance","This is a relatively popular genre which deals with the detailled creation and progression of the romantic relationship between two characters. Normally paired with comedy and harem it has developed into somewhat an industry on its own with tons of devoted followers due to the inclination for it viewers to form somewhat of a connection between themselves and one or multiple characters. Examples are Love Hina, Ai Yori Aoshi and Clannad."),
    MAGIC("Magic","Synonymous with superpower but used when referring to a more ‘kiddy’ styled anime. (young girl with magic wand etc.)  It can also be used to refer to animes with a ‘realistic’ sense of superpowers such as, results from praying, magic charms etc.  Da Capo, Twin Angel"),
    MARTIAL_ARTS("Martial Arts","Action Packed with the majority of the ‘actiony’ scenes from a form of martial arts such as boxing, kenpo or mixed martial arts. Historys Strongest Disciple Kenshi, Hajime no Ippo."),
    MECHA("Mecha","Another action packed anime genre, but with the use of giant robots or Mechas. Often includes space, military and fantasy.Mobile Suit Gundam, Neon Genesis Evangelion."),
    MILITARY("Military","Where the main character is often in the military or ex-military. Frequent use of military weapons and millitary combat knowledge, involves the action, mecha or adventure genres. Ghost in the Shell, 07-Ghost."),
    MUSIC("Music","Where the theme of the show encompasses the art of music, either where it is used to express emotion or as a hobby. Usually incorporated with the love/romance genre. NANA , Nodame Cantabile"),
    MYSTERY("Mystery","Anime Genre that keeps the views wondering whats going to happen next, usually involves a chain of unexplained events, where the protagonist tried to solve them. Normally with an above average intellect the protagonist slowly encompasses himself in the mystery and often becomes obsessed with the case. As the story unfolds the dark cloud that shrouded the answers is broken apart piece by piece letting the viewers enjoy a thrilling ride until the end. Common examples are Death Note, Monster and Darker than Black. It is very often mixed with the Psychological and Horror Genre."),
    POLICE("Police","See Military"),
    PSYCHOLOGICAL("Psychological","The genre that continues to never fail in producing anime masterpieces,  shows such as Death Note, Monster and Code Geass are all great anime psychlogical pieces. Like mystery it keeps you on the edge of your seat wondering whats next, but there is always an additional twist with the entire series seeming somewhat like a game of chess, one character trying to keep 10 steps ahead of the other. Although it goes hand in hand with the mystery genre, psychological anime tends to leave the viewer guessing till the very last moment about what will happen instead of  mystery’s way of slowly revealing truths. Overall, when it comes to an excellent story-line, this is one of the best genres out there."),
    SAMURAI("Samurai","Often (if not always) used with the historical genre with the time frame being centered around the Edo Period in Japan, often has alot of action although the element of drama is also seen due to the time setting. Can be comical i.e Gintama, and Samurai Champloo or follow a more serious mood such as Blade of the Immortal or Rurouni Kenshin."),
    SCHOOL("School"," A very common genre on the lighter side of anime, usually incorporates drama, comedy, slice of life and love/romance, typically a middle school – university setting. Anime usually progresses in chronological order (exams, summer break, first day of school etc) and typically incorporates school activities such as running/swimming/basketball etc. The mood of this genre varies a great deal depending on the level of the institution, with the level of maturity of the characters increasing respectively. Common anime which include this are The Melanchony of Haruhi Suzumiya, Beelzebub, Amagami SS and Great Teacher Onizuka."),
    SCI_FI("Sci-Fi","Very often incorporated with the fantasy, mecha and space genres, typically includes technology that may be possible in the future but currently isn’t, such as teleportation, intergalaxy space flight and advanced civilizations. Also often includes alien creatures and to some extent giant monsters or robots. Examples include Level E, Tengen Toppa Gurren Lagann and Zoids."),
    SEINEN("Seinen","Is basically an indicator of an anime aimed at the adult male (ages 18-40). They tend to usually be psychological, sexual and violent while dealing with character development and relationships in a very mature way. Examples are Cowboy Bebop, Futari Ecchiand Rainbow."),
    SHOUJO("Shoujo","Is basically an indicator of an anime aimed at the young female (ages 7-18). They tend to usually be very visual and aimed at telling a particular story, it tends to have a strong focus on romance, relationships and character development. Nana, Lovely Complex,Kare Kano and Vampire Knight."),
    SHOUJP_AI("Shoujo-ai","Relates to lesbian romance and relationships, is less graphic than Yuri(its more explicit counterpart). It tends to focus on romance, relationships and character development. Candy Boy, Simoun, Ga-Rei: Zero."),
    SLICE_OF_LIFE("Slice Of Life","Basically implies the use of mundane realism in expressing everyday life. Usually mixed with the romance, school and josei genres. Examples are Kino no Tabi, School Rumble and Ai Yori Aoshi"),
    SPACE("Space","Often incorporated with Sci-Fi and fantasy genres, and usually implies there is alot of space travel or a large amount of the show’s setting is on a space colony, or in a spacecraft eg. Planetes, Cowboy Bebop and Mobile Suit Gundam."),
    SUPER_POWER("Super Power","Action or Adventure Based where the protagonist has variety of super powers (super speed, strength, etc). Dragonball Z, Naruto."),
    SUPERNATURAL("Supernatural","Has to do with, spirits, demons and other supernatural entities, different from the magic genre as it includes more out of the ordinary characteristics such as aliens, time travel and ESPers. Natsume Yuujinchou San and Ao no Excorsist."),
    VAMPIRA("Vampire","As the name states, deals with vampires, it by default is a subcategory of the Supernatural genre but has risen in popularity to the point where it became its own genre. Common shows include Hellsing, Rosario + Vampire, Trinity Blood and Blood +."),
    YAOI("Yaoi","More explicit variation of Shounen-ai (male x male)"),
    YURI("Yuri","More explicit variation of Shojo-ai (girl x girl) ");


    private String genre;
    private String description;

    Genres(final String genre, final String description){
        this.genre= genre;
        this.description = description;
    }



}
